CREATE DATABASE IF NOT EXISTS multivendor_ecommerce;
USE multivendor_ecommerce;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS SHIPMENTS;
DROP TABLE IF EXISTS PAYMENTS;
DROP TABLE IF EXISTS ORDER_ITEMS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CART_ITEMS;
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS PRODUCT_BY_STAGE;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS VENDORS;
DROP TABLE IF EXISTS USERS;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE USERS (
  User_ID INT AUTO_INCREMENT PRIMARY KEY,
  Email VARCHAR(120) UNIQUE NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Role ENUM('Customer', 'Vendor', 'Admin') NOT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE CUSTOMERS (
  Customer_ID INT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Phone_No VARCHAR(20),
  FOREIGN KEY (Customer_ID) REFERENCES USERS(User_ID) ON DELETE CASCADE
);
CREATE TABLE VENDORS (
  Vendor_ID INT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Phone_No VARCHAR(20),
  Address VARCHAR(255),
  FOREIGN KEY (Vendor_ID) REFERENCES USERS(User_ID) ON DELETE CASCADE
);
CREATE TABLE ADDRESS (
  Address_ID INT AUTO_INCREMENT PRIMARY KEY,
  Recipient_Name VARCHAR(100) NOT NULL,
  Recipient_Phone VARCHAR(20) NOT NULL,
  Street VARCHAR(120) NOT NULL,
  City VARCHAR(60) NOT NULL,
  Pincode VARCHAR(12) NOT NULL,
  Country VARCHAR(60) NOT NULL,
  Customer_ID INT NOT NULL,
  UNIQUE KEY uq_customer_address_identity (Customer_ID, Recipient_Name, Recipient_Phone, Street, City, Pincode, Country),
  KEY idx_address_customer (Customer_ID),
  FOREIGN KEY (Customer_ID) REFERENCES CUSTOMERS(Customer_ID) ON DELETE CASCADE
);
CREATE TABLE CATEGORIES (
  Category_ID INT AUTO_INCREMENT PRIMARY KEY,
  Category_Name VARCHAR(80) UNIQUE NOT NULL
);
CREATE TABLE PRODUCTS (
  Product_ID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(120) NOT NULL,
  Description TEXT,
  Image_URL VARCHAR(500),
  Price DECIMAL(10,2) NOT NULL,
  Stock INT NOT NULL DEFAULT 0,
  Category_ID INT NOT NULL,
  Vendor_ID INT NOT NULL,
  CHECK (Price >= 0),
  CHECK (Stock >= 0),
  KEY idx_products_category (Category_ID),
  KEY idx_products_vendor (Vendor_ID),
  FOREIGN KEY (Category_ID) REFERENCES CATEGORIES(Category_ID),
  FOREIGN KEY (Vendor_ID) REFERENCES VENDORS(Vendor_ID) ON DELETE CASCADE
);
CREATE TABLE PRODUCT_BY_STAGE (
  Product_ID INT NOT NULL,
  Size VARCHAR(20) NOT NULL,
  Stock INT NOT NULL DEFAULT 0,
  PRIMARY KEY (Product_ID, Size),
  CHECK (Stock >= 0),
  FOREIGN KEY (Product_ID) REFERENCES PRODUCTS(Product_ID) ON DELETE CASCADE
);
CREATE TABLE ORDERS (
  Order_ID INT AUTO_INCREMENT PRIMARY KEY,
  Vendor_ID INT NOT NULL,
  Customer_ID INT NOT NULL,
  Order_Date DATETIME NOT NULL,
  Status VARCHAR(30) NOT NULL,
  Total_Amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  KEY idx_orders_vendor_date (Vendor_ID, Order_Date),
  KEY idx_orders_customer_date (Customer_ID, Order_Date),
  FOREIGN KEY (Vendor_ID) REFERENCES VENDORS(Vendor_ID),
  FOREIGN KEY (Customer_ID) REFERENCES CUSTOMERS(Customer_ID)
);
CREATE TABLE ORDER_ITEMS (
  Order_Item_ID INT AUTO_INCREMENT PRIMARY KEY,
  Order_ID INT NOT NULL,
  Product_ID INT NOT NULL,
  Quantity INT NOT NULL,
  Price_At_Purchase DECIMAL(10,2) NOT NULL DEFAULT 0,
  Status VARCHAR(30) NOT NULL,
  CHECK (Quantity > 0),
  CHECK (Price_At_Purchase >= 0),
  KEY idx_order_items_order (Order_ID),
  KEY idx_order_items_product (Product_ID),
  FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID) ON DELETE CASCADE,
  FOREIGN KEY (Product_ID) REFERENCES PRODUCTS(Product_ID)
);
CREATE TABLE PAYMENTS (
  Payment_ID INT AUTO_INCREMENT PRIMARY KEY,
  Payment_Mode VARCHAR(30) NOT NULL,
  Payment_Date DATETIME,
  Payment_Status VARCHAR(30) NOT NULL,
  Order_ID INT NOT NULL,
  KEY idx_payments_order (Order_ID),
  FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID) ON DELETE CASCADE
);
CREATE TABLE SHIPMENTS (
  Shipment_ID INT AUTO_INCREMENT PRIMARY KEY,
  Order_ID INT NOT NULL,
  Address_ID INT NOT NULL,
  Tracking_Number VARCHAR(80),
  Status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  Shipped_At DATETIME,
  Delivered_At DATETIME,
  UNIQUE KEY uq_shipment_order (Order_ID),
  UNIQUE KEY uq_shipment_tracking (Tracking_Number),
  KEY idx_shipments_status (Status),
  FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID) ON DELETE CASCADE,
  FOREIGN KEY (Address_ID) REFERENCES ADDRESS(Address_ID)
);
CREATE TABLE REVIEW (
  Review_ID INT AUTO_INCREMENT PRIMARY KEY,
  Customer_ID INT NOT NULL,
  Product_ID INT NOT NULL,
  Rating INT NOT NULL,
  Text TEXT,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (Rating BETWEEN 1 AND 5),
  UNIQUE KEY uq_review_customer_product (Customer_ID, Product_ID),
  KEY idx_review_product (Product_ID),
  FOREIGN KEY (Customer_ID) REFERENCES CUSTOMERS(Customer_ID) ON DELETE CASCADE,
  FOREIGN KEY (Product_ID) REFERENCES PRODUCTS(Product_ID) ON DELETE CASCADE
);
CREATE TABLE CART (
  Cart_ID INT AUTO_INCREMENT PRIMARY KEY,
  Customer_ID INT UNIQUE NOT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Customer_ID) REFERENCES CUSTOMERS(Customer_ID) ON DELETE CASCADE
);
CREATE TABLE CART_ITEMS (
  Cart_Item_ID INT AUTO_INCREMENT PRIMARY KEY,
  Cart_ID INT NOT NULL,
  Product_ID INT NOT NULL,
  Product_Name VARCHAR(150) NOT NULL,
  Quantity INT NOT NULL,
  UNIQUE KEY uq_cart_product (Cart_ID, Product_ID),
  CHECK (Quantity > 0),
  KEY idx_cart_items_product (Product_ID),
  FOREIGN KEY (Cart_ID) REFERENCES CART(Cart_ID) ON DELETE CASCADE,
  FOREIGN KEY (Product_ID) REFERENCES PRODUCTS(Product_ID) ON DELETE CASCADE
);
